### ISSUE TITLE
How to report function timeout more usefully?

### ISSUE THREAD

**Issue by rick-schubert** [rquellh/testcafe-cucumber#1]
Hi @rquellh ,

Thank you so much for this, I really like it! I took a lot of inspiration from you and also started doing my own cucumber-testcafe suite.

I have one question though: do you know how I report function timeouts properly? Let's say I have an element on a page (`Selector`) and testcafe waits for it 20 seconds but doesn't find it - Cucumber then in that case will just report "a function timed out", wheras testcafe would have said on which line it stopped. Is it somehow possible to access the testcafe report as well as the cucumber reporting?

I already tried it with the reporters specified by testcafe in the runner API, but they all don't log anything - only the `list` reporter prints out anything at all something, but this is only restricted to "Running tests on Chrome / Windows 10" and "Ran 1 test successfully" in the end.

```javascript
const stream = fs.createWriteStream('report.json');

runner
    .src('tests/sample-fixture.js')
    .browsers('chrome')
    .reporter('json', stream)
    .reporter('list')
    .run()
    .then(failedCount => {
        stream.end();
    });
```

**Comment by rquellh** [comment]
Hi Rick

Thanks for checking out my repo. 

Could you give me an example of would you'd like to see in the console? Also, could you give me an example of what you are currently seeing?

**Comment by rick-schubert** [comment]
@rquellh , thanks for the swift reply! I would like to get access to the original testcafe reporter, i.e.:

```
 ✖ User registers and makes a purchase (screenshots:
 /Users/schuber/Documents/github/testcafe-without-cucumber/screenshots/2018-02-26_08-41-41/test-1)

   1) AssertionError: PDP didn't fully load. See call trace above.: expected false to be truthy

      Browser: Chrome 64.0.3282 / Mac OS X 10.12.6
      Screenshot:

   /Users/schuber/Documents/github/testcafe-without-cucumber/screenshots/2018-02-26_08-41-41/test-1/Chrome_64.0.3282_Mac_OS_X_10.12.6/errors/1.png

         13 |
         14 |    async waitToBeLoaded() {
         15 |        this.characteristicPageElements.forEach(async (element) => {
         16 |            await this.testController
         17 |                .expect(element.exists)
       > 18 |                .ok(
         19 |                    `${this.pageTitle} didn't fully load. See call trace above.`
         20 |                )
         21 |        })
         22 |    }
         23 |}

         at <anonymous> (/Users/schuber/Documents/github/testcafe-without-cucumber/pageObjects/base.page.js:18:18)
         at _this.characteristicPageElements.forEach
      (/Users/schuber/Documents/github/testcafe-without-cucumber/pageObjects/base.page.js:15:9)
         at <anonymous> (/Users/schuber/Documents/github/testcafe-without-cucumber/pageObjects/base.page.js:15:41)
         at PDP.waitToBeLoaded (/Users/schuber/Documents/github/testcafe-without-cucumber/pageObjects/base.page.js:14:28)
         at <anonymous> (/Users/schuber/Documents/github/testcafe-without-cucumber/pageObjects/navigation.page.js:45:19)
```

**Comment by rquellh** [comment]
This is now resolved in the current version of the repo.

**Comment by rquellh** [comment]
This is now resolved in the current version of the repo.
