### ISSUE TITLE
Features folder restructuring - Bring pages, step_def and features file under e2e_tests

### ISSUE THREAD

**Issue by vvedachalam** [rquellh/testcafe-cucumber#12]
Hi 
I renamed the features folder to e2e_tests, created features folder under e2e_tests and moved all the features file under features folder  I change the path name for TestController and errorHandling as below 
fs.writeFileSync('test.js',
        'import errorHandling from "./e2e_tests/support/errorHandling.js";\n' +
        'import testControllerHolder from "./e2e_tests/support/testControllerHolder.js";\n\n' +

If I run the a scenario or feature, it I am not getting error but none of the steps are executed
$ node ./node_modules/.bin/cucumber-js
(node:1491) ExperimentalWarning: The fs.promises API is experimental

0 scenarios
0 steps
0m00.000s
Done in 0.32s.

Any idea?
Thanks

**Comment by vvedachalam** [comment]
@rquellh Are you using this framework or abandoned for some reasons? I continue to work in TC and thought it will be great to know if someone else also in the same boat

**Comment by rquellh** [comment]
@vvedachalam My current workload doesn't involve UI testing, so I haven't been using TestCafe as in my day to day like I did at the beginning of the year. I still think TestCafe is still the best tool for UI based E2E testing.

**Comment by bhreinb** [comment]
Hi @vvedachalam I want to use cucumberjs and testcafe together as a toolset but having the same issue as yourself support is very limited 👎

**Comment by rquellh** [comment]
I modeled the folder structure after the book [Cucumber and Cheese](https://leanpub.com/cucumber_and_cheese) by Jeff Morgan, because this is the folder structure that is most frequently used in my area. 

Feel free to fork this repo and restructure as you please, but I think for now I'll keep the current structure.

**Comment by vvedachalam** [comment]
@bhreinb let me know if you need any support
@rquellh Yes, thats what I am doing. cheers

**Comment by bhreinb** [comment]
Hello @vvedachalam 

I implemented non standard folder structure easily enough. You can see a sample of how I did it here at this link

https://github.com/bhreinb/SYSTAC

**Comment by vvedachalam** [comment]
@bhreinb Cool one
