### ISSUE TITLE
Passing parameters

### ISSUE THREAD

**Issue by valen-tina** [rquellh/testcafe-cucumber#28]
Hi there,
I'm wondering is there a way to make parametrization of step? 
What I mean is to pass an array to the scenario or step and run the scenario several times with every element from array? 

Thanks

**Comment by rquellh** [comment]
I think you are looking for a scenario outline https://cucumber.io/docs/gherkin/reference/#scenario-outline.

What you are describing is one of the benefits of using cucumber to control test flow. Let me know if you are struggling with the concepts and maybe I can provide an example.

**Comment by valen-tina** [comment]
Great! That's exactly what I need. Thank you!
